name = "prod-hono-crud"
compatibility_date = "2024-08-23"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "1c83c2f4-ec65-4ec3-8699-15ed7316a5ff"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "prod-hono-crud"
database_id = "1c83c2f4-ec65-4ec3-8699-15ed7316a5ff"

# [ai]
# binding = "AI"